version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/e2e/...'
      REPO_URL: 'https://github.com/openmcp-project/openmcp-testing'

tasks:
  e2e:
    desc: "Run end-to-end tests"
    cmds:
      - go test -v ./e2e/... -count=1