version: 3

includes:
  shared:
    taskfile: hack/common/Taskfile_library.yaml
    flatten: true
    vars:
      CODE_DIRS: '{{.ROOT_DIR}}/internal/... {{.ROOT_DIR}}/pkg/... {{.ROOT_DIR}}/e2e/...'
      GENERATE_DOCS_INDEX: "true"